# 1.Print 'Hello HCIA'.

In [1]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [3]:
a = 5
b = 3
sum = 5+3
print(sum)

8


# 3.Define a list and replicate in three different ways.

In [16]:
a = ['I', 'love', 'Paimon', '!']
print(a)
print([a]*2)
for i in range(5):
    print(a)

['I', 'love', 'Paimon', '!']
[['I', 'love', 'Paimon', '!'], ['I', 'love', 'Paimon', '!']]
['I', 'love', 'Paimon', '!']
['I', 'love', 'Paimon', '!']
['I', 'love', 'Paimon', '!']
['I', 'love', 'Paimon', '!']
['I', 'love', 'Paimon', '!']


# 4.Define two lists and merge them together.

In [6]:
list1 = ['New', 'K/DA','song', '-']
list2 = ['"MORE"']
list3 = list1 + list2
print(list3)

['New', 'K/DA', 'song', '-', '"MORE"']


# 5. Get the last element of the list and print it.

In [7]:
lol = ['My', 'favotite', 'character', 'is', 'Sona']
print(lol[4])

Sona


# 6.Define a tuple that contains only one element.

In [9]:
something = ('love')
print(something)

love


# 7.Define a three-line long string.

In [18]:
print('Как у вас дела? \n Надеюсь, вы хорошо себя чувствуете. \n Не болейте!')

Как у вас дела? 
 Надеюсь, вы хорошо себя чувствуете. 
 Не болейте!


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [13]:
vera = ('I', 'love', 'sing')
for i in range(3):
    print(vera[i])

I
love
sing


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [17]:
from operator import mul
mul = mul(4,5)
print(mul)

20


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [29]:
import numpy as np
s=(5,5)
zero = np.zeros(s)
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [30]:
import numpy as np
s=(4,6)
zerotwo = np.zeros(s)
print(zerotwo)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [21]:
import numpy as np
a=np.arange(15,)
print(a)
a=np.arange(3,5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[3 4]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [25]:
import numpy as np
a = np.array([ [1, 2, 3], [4, 5, 6] ])
b = np.array([[1,1], [2,2],[3,3]])
total = a.dot(b)
print(total)

[[14 14]
 [32 32]]
